outbarriers/outbarriers/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from ficha import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<slug>[-\w]+)/$', views.DetailView.as_view(), name='detalle'),


]

outbarriers/ficha/models.py
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver

class Etiqueta(models.Model):
    """Modelo para representar etiquetas asociadas a locales"""
    name = models.CharField(max_length=25, unique=True)

    class Meta:
        db_table = 'etiquetas'
        ordering = ('name',)

    def __str__(self):
        return u'%s' % self.name


class Ficha(models.Model):
    """Modelo para representar la ficha de un local."""
    BAR = 1
    RETAIL = 2
    OTHER = 3
    KIND_CHOICES = (
        (BAR, 'bar'),
        (RETAIL, 'retail'),
        (OTHER, 'other'),
    )
    dt = models.DateTimeField(auto_now_add=True)
    dtMod = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=30, unique=True)
    name = models.CharField(max_length=255, verbose_name="Nombre")
    kind = models.IntegerField(choices=KIND_CHOICES, default=OTHER, verbose_name="Tipo")
    description = models.TextField(verbose_name="Descripcion")
    logo = models.ImageField(null=False, upload_to='ficha/logos', max_length=24576, verbose_name="Logo")
    image = models.ImageField(null=False, upload_to='ficha/img', max_length=24576, verbose_name="Imagen")
    tags = models.ManyToManyField(Etiqueta, blank=True, verbose_name="Etiquetas")

    class Meta:
        db_table = 'fichas'
        ordering = ('name',)

    def __str__(self):
        return u'%s' % self.name


@receiver(post_delete, sender=Ficha)
def ficha_delete(sender, instance, **kwargs):
    """Borra los ficheros de las fichas que se eliminan"""
    instance.image.delete(False)
    instance.logo.delete(False)

outbarriers/ficha/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic

from .models import Ficha

class IndexView(generic.ListView):
    template_name = 'ficha/index.html'
    context_object_name = 'fichas'

    def get_queryset(self):
        return Ficha.objects.order_by('name')

class DetailView(generic.DetailView):
    model = Ficha
    template_name = 'ficha/detalle.html'

outbarriers/ficha/templates/ficha/detalle.html
{% extends 'base.html' %}
{% load staticfiles %}

{% if ficha %}
  {% block header %}
      <h1 class="pull-right">{{ ficha.name }}</h1>
  {% endblock%}

  {% block content %}
    <div class="row border-line">
    <div class="col-md-6 border-right">
      <div class="row">
        <img src="/static/{{ ficha.image.url }}" class="img-responsive center-block" alt="{{ ficha.name }}" />
        <!-- <img src="{% static "ficha/imagenes/mapa.png" %}" class="img-responsive center-block" alt="{{ ficha.name }}" />-->
      </div>
      <div class="row">
        <img src="{% static "images/mapa.png" %}" class="img-responsive center-block" alt="{{ ficha.name }}" />
      </div>
    </div>
    <div class="col-md-6">
      <div class="row">
        <h1 class="page-header pull-right">{{ ficha.get_kind_display }}</h1>
      </div>
      <div class="row">
        <p>{{ ficha.description }}</p>
      </div>
      <div class="row">
        {% if ficha.tags %}
        <p>
          {% for t in ficha.tags.all %}
            {{ t.name }}
          {% endfor %}
        </p>
        {% else %}
          <p></p>
        {% endif%}
      </div>
    </div>

  </div>
  {% endblock %}

{% else %}
  <p>No hay datos para este local.</p>
{% endif %}

outbarriers/ficha/templates/ficha/index.html
{% extends 'base.html' %}

{% block content %}
{% if fichas %}
  {% for f in fichas %}
    <div class="col-md-3 item">
      <a href="{{ f.slug }}">
          <img class="img-responsive" src="/static/{{ f.logo.url }}" alt="{{ f.name }}">
      </a>
    </div>
  {% endfor %}
{% else %}
    <p>No hay locales disponibles.</p>
{% endif %}
{% endblock %}

outbarriers/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Los 40 locales esenciales de Outbarriers">
    <meta name="author" content="Outbarriers">
  <title> {% block title %} Los 40 de Outbarriers {% endblock %}</title>
  {% load staticfiles %}
  <!-- Bootstrap Core CSS -->
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" media="screen">

  <!-- Custom CSS -->
    <link href="{% static "css/outbarriers.css" %}" rel="stylesheet">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
  {% load staticfiles %}

    <section class="container">
      <header class="row">
        <div class="col-lg-12">
            {% block header%}
                <h1 class="page-header">Los 40 de Outbarriers</h1>
            {% endblock%}
        </div>
      </header>
      <section class="row">
        {% block content %}
        <div class="row">
           <div class="col-md-3 item">
               <a href="#">
                   <img class="img-responsive" src="http://placehold.it/250x150" alt="">
               </a>
           </div>
           <div class="col-md-3 item">
               <a href="#">
                   <img class="img-responsive" src="http://placehold.it/250x150" alt="">
               </a>
           </div>
           <div class="col-md-3 item">
               <a href="#">
                   <img class="img-responsive" src="http://placehold.it/250x150" alt="">
               </a>
           </div>
           <div class="col-md-3 item">
               <a href="#">
                   <img class="img-responsive" src="http://placehold.it/250x150" alt="">
               </a>
           </div>

       </div>
       {% endblock %}
      </section>
      <footer class="row">

          <div class="col-md-4 col-lg-4">
            <img src="{% static "images/twitter.png" %}" alt="Siguenos en Twitter" />
            <img src="{% static "images/facebook.png" %}" alt="Siguenos en Facebook" />
          </div>
          <div class="col-md-4 col-lg-4">
            <img class="center-block" src="{% static "images/los-40-esenciales.png" %}" class="img-responsive" alt="Los 40 esenciales" />
          </div>
          <div class="col-md-4 col-lg-4">
            <img class="pull-right" src="{% static "images/logo_outbarriers.png" %}" class="img-responsive" alt="Outbarriers" />
          </div>
      </footer>
  </section>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</body>
</html>